from langchain_google_genai import ChatGoogleGenerativeAI
from src.core.settings import Settings as settigns

llm = ChatGoogleGenerativeAI(
    model=settings.llm_model
    temperature=...
    max_tokens=...
    timeout=...
    max_retries=...
)

#calor, poblacion, urbe