"""initial tables

Revision ID: 0ad824d32f29
Revises: 
Create Date: 2025-10-05 03:50:37.747495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad824d32f29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urban_quality',
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('POBTOT', sa.Integer(), nullable=False),
    sa.Column('GRAPROES', sa.Float(), nullable=False),
    sa.Column('GRAPROES_F', sa.Float(), nullable=False),
    sa.Column('GRAPROES_M', sa.Float(), nullable=False),
    sa.Column('RECUCALL_C', sa.Integer(), nullable=False),
    sa.Column('RAMPAS_C', sa.Integer(), nullable=False),
    sa.Column('PASOPEAT_C', sa.Integer(), nullable=False),
    sa.Column('BANQUETA_C', sa.Integer(), nullable=False),
    sa.Column('GUARNICI_C', sa.Integer(), nullable=False),
    sa.Column('CICLOVIA_C', sa.Integer(), nullable=False),
    sa.Column('CICLOCAR_C', sa.Integer(), nullable=False),
    sa.Column('ALUMPUB_C', sa.Integer(), nullable=False),
    sa.Column('LETRERO_C', sa.Integer(), nullable=False),
    sa.Column('TELPUB_C', sa.Integer(), nullable=False),
    sa.Column('ARBOLES_C', sa.Integer(), nullable=False),
    sa.Column('DRENAJEP_C', sa.Integer(), nullable=False),
    sa.Column('TRANSCOL_C', sa.Integer(), nullable=False),
    sa.Column('ACESOPER_C', sa.Integer(), nullable=False),
    sa.Column('ACESOAUT_C', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('sessions',
    sa.Column('parametros', sa.JSON(), nullable=False),
    sa.Column('csv_url', sa.String(length=2048), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('users')
    op.drop_table('urban_quality')
    # ### end Alembic commands ###
