"""create margined population charts

Revision ID: 11628c9d4786
Revises: dfd978ffe005
Create Date: 2025-10-05 05:22:49.525817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11628c9d4786'
down_revision: Union[str, Sequence[str], None] = 'dfd978ffe005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unequality_indicators',
    sa.Column('cve_ent', sa.Integer(), nullable=False),
    sa.Column('cve_mun', sa.Integer(), nullable=False),
    sa.Column('cve_sun', sa.String(length=12), nullable=False),
    sa.Column('cvegeo', sa.String(length=20), nullable=False),
    sa.Column('sun', sa.String(length=128), nullable=False),
    sa.Column('gmu', sa.String(length=32), nullable=True),
    sa.Column('iisu_sun', sa.String(length=32), nullable=True),
    sa.Column('iisu_cd', sa.String(length=32), nullable=True),
    sa.Column('Pob_2010', sa.Integer(), nullable=False),
    sa.Column('Empleo', sa.Integer(), nullable=True),
    sa.Column('E_basica', sa.Integer(), nullable=True),
    sa.Column('E_media', sa.Integer(), nullable=True),
    sa.Column('E_superior', sa.Integer(), nullable=True),
    sa.Column('Salud_cama', sa.Integer(), nullable=True),
    sa.Column('Salud_cons', sa.Integer(), nullable=True),
    sa.Column('Abasto', sa.Integer(), nullable=True),
    sa.Column('Espacio_ab', sa.Integer(), nullable=True),
    sa.Column('Cultura', sa.Integer(), nullable=True),
    sa.Column('Est_Tpte', sa.Integer(), nullable=True),
    sa.Column('geometry', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cvegeo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unequality_indicators')
    # ### end Alembic commands ###
